baseURL = "https://devmycloud.github.io/MyCloudAPI-DOC/"
#baseURL = "http://localhost/MyCloudAPI-DOC/"
languageCode = "en-us"
title = "MyCloudFulfillment API Documentation"
relativeURLs = "true"

[params]
binary_version = "0.7.6"
